[programs.mainnet]
distribution = "2YkXmCtRc6BzST3eavg7pxnYRJmoMBXEB8pzDN77wuhN"
[programs.devnet]
distribution = "2YkXmCtRc6BzST3eavg7pxnYRJmoMBXEB8pzDN77wuhN"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/fury/deploy-231218.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
